<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQR7IVRK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQR7IVRK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQR7IVRK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQR7IVRK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQR7IVRK\App_KernelDevDebugContainer([
    'container.build_hash' => 'QR7IVRK',
    'container.build_id' => '6a9ffd34',
    'container.build_time' => 1673433098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQR7IVRK');
